#!/bin/bash
echo "https://www.google.com/search?q=confused+smiley&sxsrf=ALeKk02qD-GqhOEC8RS_q9NKgabeMKzB9Q:1629711143109&tbm=isch&source=iu&ictx=1&fir=t5Wzk4I2Gk-dfM%252CbR6aOyMGfxOqMM%252C_&vet=1&usg=AI4_-kRZCTGbtHb3RTz4swRZX9cQO4kzlw&sa=X&ved=2ahUKEwidwJWO68byAhVP14UKHWxBBQMQ9QF6BAgIEAE#imgrc=t5Wzk4I2Gk-dfM"/n
