#!/usr/bin/env bash
# script that will display information about subdomains
# awk '{print $4}' is A record and $5 is the IP address
custom_fn ()
{
    for arg
    do
	echo -n "The subdomain $arg is a "
	dig $arg."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4 " record and points to " $5}'
    done
}

domain="$1"
# sbdmain="$2"
if [ $# -eq 1 ]; then
    custom_fn www lb-01 web-01 web-02
else
    sbdmain="$2"
    custom_fn "$sbdmain"
fi
