#!/usr/bin/env bash
# script that will display information about subdomains
# awk '{print $4}' is A record and $5 is the IP address
info_Domain () {
    A=$(dig $2.$1 | awk '/ANSWER SECTION:/{getline;print;}')
    RE=$(echo $A | cut -d' ' -f 4)
    IP=$(echo $A | cut -d' ' -f 5)
    echo "The subdomain $2 is a $RE record and points to $IP"
}
if [ $# -lt 1 ]
then
    echo "Usage: 1-world_wide_web DOMAIN SUBDOMAIN(optional)"
elif [ $# -eq 1 ]
then
    info_Domain "$1" "www"
    info_Domain "$1" "lb-01"
    info_Domain "$1" "web-01"
    info_Domain "$1" "web-02"
else
    info_Domain "$1" "$2"
fi
