#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get update -y
apt-get install -y haproxy=1.6.\*

CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 1206-web-01 34.75.163.65:80 check
	server 1206-web-02 3.229.120.59:80 check
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
