#!/usr/bin/env bash
# Nginx likes port 80
# /s: search and replace the pattern regexp
# /g: stands for global, which means that all matching occurrences
# in the line would be replaced
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restarti
