#!/usr/bin/env bash
# Bash script that gives you information about the school file

file1="school"
if [ -e "$file1" ]
then
    echo "$file1 file exists"
    if [ -s "$file1" ]
    then
        echo "$file1 file is not empty"
    else
        echo "$file1 file is empty"
    fi
    if [ -f "$file1" ]
    then
        echo "$file1 is a regular file"
    fi
else
    echo "$file1 file does not exist"
fi
