#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
chmod 204 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
